### ISSUE TITLE
GRPC Error on many simultaneous connections

### ISSUE THREAD

**Issue by paulrostorp** [dgraph-io/dgraph-js#109]
Hi all,
I'm getting ```Error: 14 UNAVAILABLE: Received RST_STREAM with error code 7```

When running a high number of parallel queries using the dgraph-js client. 
I get no errors with a few simultaneous queries, but past a certain threshold (occurs above ~= 600-1200) the transactions return the above error.

My dgraph cluster is running at very low resource utilization (i.e not even close to being overloaded) and there is nothing of use in the alpha's logs...

I'm using dgraph-js@2.1.0, my dgraph cluster is v2.0.0-rc1

Do you have any ideas how to debug this ?

**Comment by paulrostorp** [comment]
I setup another cluster with dgraph:v1.2.1 and the error is still occurring the same. I also setup tracing and no errors in jaeger...

Still nothing in the Alpha logs though...

**Comment by paulrostorp** [comment]
Further experimenting led me to discover that if I run my node program as multiple parallel processes, each run 500 simultaneous queries, everything works perfectly.
I literally just did this:
```yarn run dev & yarn run dev & yarn run dev & yarn run dev & yarn run dev & yarn run dev```

So this leads me to believe that this has something to do with a node limit for grpc...

**Comment by paulrostorp** [comment]
Tracing for the error shows: 
<img width="1355" alt="Screenshot 2020-03-06 at 13 26 21" src="https://user-images.githubusercontent.com/1866649/76083526-2355df80-5fae-11ea-8c86-4a601d32eb0d.png">

**Comment by paulrostorp** [comment]
I enabled GRPC logs on server (GRPC_GO_LOG_SEVERITY_LEVEL=info
GRPC_GO_LOG_VERBOSITY_LEVEL=2) and now I see errors :

```INFO: 2020/03/06 12:40:16 transport: loopyWriter.run returning. connection error: desc = "transport is closing"```

**Comment by shynome** [comment]
from https://github.com/grpc/grpc-node/issues/1158#issuecomment-565335385

> After moving from node 12 to node 13, we no longer have the issue.

@paulrostorp  maybe you can have a try

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8191). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
