### ISSUE TITLE
Module import requires unsafe-eval in script content security policy directive

### ISSUE THREAD

**Issue by ghost** [dgraph-io/dgraph-js#115]
I'm trying to import the module in an Electron application with a recommended `Content Security Policy` of `script-src 'self'` but it prevents loading of the module with the error below.

![screenshot-20200427033648160881813](https://user-images.githubusercontent.com/37121652/80326375-d6b5b480-8838-11ea-9af3-8512a27a8525.png)

It loads if I add `'unsafe-eval'` to the policy, but I get reminded of the security risk.

![screenshot-20200427033704155928453](https://user-images.githubusercontent.com/37121652/80326465-2c8a5c80-8839-11ea-80bf-c216b74f2796.png)

Is there a way around this or should an Electron application use the `dgraph-js-http` package instead? I've read [in this blog post](https://dgraph.io/blog/post/building-todo-list-react-dgraph/) that _"For many use cases, the difference in performance is negligible"_.

Would that apply to an Electron application using a single Dgraph instance locally?

```
dgraph-js: 20.3.0
```

**Comment by prashant-shahi** [comment]
I would recommend you use to [dgraph-js-http](https://github.com/dgraph-io/dgraph-js-http) instead.

You can check out this sample electron app which makes use of `dgraph-js-http` client.
https://github.com/prashant-shahi/electron-todo

**Comment by ghost** [comment]
Thank you for the fast response and for providing an example I can work off of! :man_dancing: 

I was hoping for the `dgraph-js-http` recommendation to avoid the `electron-rebuild` and `electron@9.0.0-beta.5-6 onwards` context aware requirement for `grpc` which I'd have ran head first into.
