### ISSUE TITLE
RFC: enhancement over dgraph schema

### ISSUE THREAD

**Issue by ghost** [dgraph-io/dgraph-js#117]
**Overview**
Users should be able to define DGraph schema in object format. Defining schema in an object format will enable us to provide more validations to the schema in a clearer way like validation for each predicate, e.g.
```js
UserSchema = new DgraphSchema({
    username: {
        type: 'String',
        index: true,
        immutable: true
    },

    password: {
        type: 'Password',
        min: 6,
        max: 26
    },
})
````

**Motivation**
A big motivation for such a feature comes from the package `mongoose` which a MongoDB client for javascript. 

**Action Items**
- [ ] Support `DgraphSchema` in an object format
- [ ] Provide basic validation options such as:
  - [ ] `immutable: [true | false]`
  - [ ] `min: [int]` and `max: [int]`
  - [ ] `unique: [true | false]`
  - [ ] `required: [true | false]`
  - [ ] `match: [new RegExp()]`
  - [ ] `default: [any]` // default value for the predicate
  - [ ] `lowercase: [true | false]` // change the string to lowercase before saving into the DB
  - [ ] `uppercase: [true | false]` // change the string to uppercase before saving into the DB
- [ ] return formatted error if provided data fails against the schema

**Comment by ghost** [comment]
I am happy to contribute but I will be needing some guidance. If anyone here would like to work on this with me please let me know.

**Comment by jarifibrahim** [comment]
cc @vardhanapoorv

**Comment by vardhanapoorv** [comment]
Hi @shreyansh-zazz 
I like the idea. You can raise a draft PR (also include an example) and I can help you with your questions.

**Comment by ghost** [comment]
Before proceeding, we have to make a decision on `DgraphClient`. There are two options as follows:

1. `new Dgraph.createClient(..args)` will create a single DB client instance and all further communications with the database will be done using this client. (current approach)
2. Let Option 1 be there and we can also expose an API such as `Dgraph.connect(...args)` which will take the same arguments as `createClient(...args)`. The only difference will be that `Dgraph.connect(...args)` will set the default DB connection, meaning we can directly use `Dgraph.Mutation()`, `Dgraph.Model()` etc.

Here I am missing the `DgraphClientStub` because I don't really understand why we need this when we can simply use `Dgraph.createClient()`

**Comment by ghost** [comment]
Also, I think the API is pretty complicated. Maybe we can try to simplify that? There are too many new variable creations to perform one simple mutation, to be honest.

There must be some reason that I am not aware of for this decision, @vardhanapoorv can you explain to me little about this, please?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8195). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
