### ISSUE TITLE
Has anybody tried dgraph-js with Dgraph v1.*?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph-js#13]
Just wondering if anybody tried `dgraph-js` with the latest version of dgraph? If so, does it work or not really?

**Comment by MichelDiz** [comment]
Work, I'm using it since 1.0

**Comment by The-Punk-Programmer** [comment]
I tried it this morning with the simple example that is on the repo and it works fine. I'll have to try and do more complex things with dgraph-js to see just how well it really works though.

**Comment by gpahal** [comment]
Yes, the client is compatible with Dgraph v0.9.x and v1.0.x
