### ISSUE TITLE
Error: Received message larger than max

### ISSUE THREAD

**Issue by tkdave** [dgraph-io/dgraph-js#22]
We are getting an error in the JS client using grpc 
“Received message larger than max (4194538 vs. 4194304)“. 

I noticed that this limitation was addressed in the golang client. 
https://github.com/dgraph-io/dgraph/issues/396

Can we open this up on the JS client as well?

Looks like the ability to pass option to the client was added 5 days ago. 
https://github.com/dgraph-io/dgraph-js/commit/f3bde42862d9c1109cf67fdf62c77fa6ae0f1627  

Wondering if I can pass an option in like this: 
https://github.com/grpc/grpc/issues/8098

Do these options flow through to the grpc client, or is it a different set of options?

We'd like to be able to do something like this:
```
  const clientStub = new DgraphClientStub(
    server, 
    credentials.createInsecure(), 
    {'grpc.max_receive_message_length': 1024 * 1024 * 1024}
  )
```
(updated with working config setting)

**Comment by gpahal** [comment]
Yes, you can pass options to `DgraphClientStub` as a 3rd argument. They are passed to the grpc client.

**Comment by tkdave** [comment]
This worked for me once I upraded dgraph client to 1.0.4 and changed my grpc option to 'grpc.max_receive_message_length'. Thanks.
