### ISSUE TITLE
How to specify @lang in setSetJson() object?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph-js#23]
Hello! I cannot find this in the README.md but how do we go about passing the language for a predicate in the json object we want to mutate?
```
{
<0f27fd12> <label@en> "Dog" .
<0f27fd12> <label@fr> "Chien" .
}
```
How do basically do this with the `Mutation.setSetJson(obj)`'s object?

p.s. and also how to delete `label@en` using the setDeleteJson()?

**Comment by pawanrawal** [comment]
The JSON below should work for setting and deleting.
```
{
  "uid" : "0f27fd12",
  "label@en": "Dog",
  "label@fr": "Chien"
}
```
