### ISSUE TITLE
After upgrading to grpc v1.9: "Error: Argument mismatch in makeUnaryRequest"

### ISSUE THREAD

**Issue by cyphercider** [dgraph-io/dgraph-js#24]
Versions:
dgraph-js: 1.1.0
dgraph: 1.0.2 or 1.0.3

This error happens when trying to perform any query against the database, after upgrading from grpc 1.8.4 to grpc 1.9.  I downgraded to 1.8.4 and the problem goes away.  Would be interested to know if anyone else can reproduce this.

**Comment by gpahal** [comment]
Fixed in the latest beta. I will release a stable version soon. You can install the beta using `npm install dgraph-js@1.1.1-beta.2`.

**Comment by cyphercider** [comment]
Confirmed fixed.  Thanks!
