### ISSUE TITLE
Can getLatency() be made available on mutation response "Assigned" class?

### ISSUE THREAD

**Issue by cyphercider** [dgraph-io/dgraph-js#26]
getLatency() is very helpful for query operations.  However, to measure performance, and separate network latency from database latency, we need to have the getLatency() function on mutation responses as well as query responses.

Can getLatency() be made available on the Assigned class as well?

**Comment by gpahal** [comment]
This client library uses grpc to communicate with the Dgraph server. But the Dgraph server doesn't expose latency metrics for a mutation. So this is not possible until Dgraph server supports this.

**Comment by gpahal** [comment]
You can create an issue on the main dgraph repo regarding this.

**Comment by cyphercider** [comment]
@gpahal , FYI, pawan just merged this into master.

https://github.com/dgraph-io/dgraph/issues/2146#issuecomment-370678072

**Comment by gpahal** [comment]
Support added in master with commit https://github.com/dgraph-io/dgraph-js/commit/eef5bbdfda8983f20bb4612ff5df5efb6c934b5f

**Comment by cyphercider** [comment]
@gpahal thanks, can I get this with some tag on NPM?

**Comment by gpahal** [comment]
I've published `v1.1.2-beta.1` with the `next` tag. So, `npm install dgraph-js@next --save` should work.

**Comment by cyphercider** [comment]
@gpahal Thanks - I will plan to test as soon as I can get the latest dgraph master on dockerhub.  Closing for now.

**Comment by pawanrawal** [comment]
The latest image has been pushed to docker hub. Give it a try now @tamethecomplex.

**Comment by cyphercider** [comment]
@pawanrawal Looks good to me, thanks!
