### ISSUE TITLE
Fetch health condition (enhancement)

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph-js#27]
Is it possible to add a fetch to the health condition of the instance?

I would like to make routine checks within my application. 
Without having to turn to Prometheus / Grafana.

In my case, the Dgraph Server instance and Zero are behind an API. I do not expose them. I've tried using isomorphic-fetch but the result format is not compatible. And as I'm using Rancher, it gets tricky to keep exact internal domainname.

```js
fetch('http://192.168.1.200:8089/health')
  .then(function(response) {
    if (response.status >= 400) {
      throw new Error('Bad response from server');
    }
    return response.json();
  })
  .then(function(response) {
    console.log(response.json());
  });
```

It would be possible?

Thanks.

Cheers.

**Comment by manishrjain** [comment]
If an external Dgraph client can talk to these servers, then you could potentially use some HTTP client to query for health.

**Comment by MichelDiz** [comment]
Actually instances with the Dgraph stack are behind a Reverse Proxy. I did not want to open a public endpoint for it. An internal kind of "ping" from the client would help in this case.

But in the impossibility, no problem. It's just a case.

**Comment by gpahal** [comment]
But the client also requires you to open a public grpc port. Is the client also behind the proxy?

**Comment by MichelDiz** [comment]
I'm not using gRPC in my own user client. I'm query through a Graphql gateway. So That way I can take advantage of an Apollo (apollographql). 

PS. We can see /health through grpc??

**Comment by MichelDiz** [comment]
Another point is that I'm using Rancher. Often times when upgrade the instances to a more current version or even restart the service or any other task. The IPs change, although Rancher has an internal DNS sometimes inconsistent.

**Comment by manishrjain** [comment]
This seems a bit specific use case to be added for general usage. @MichelDiz , I'm sure you can find a way around this, and use the HTTP based health checker.

**Comment by MichelDiz** [comment]
I'll try this https://github.com/dgraph-io/dgraph/blob/0cbe6030569452f29dbaab6e37a2311b4800b71c/dashboard/src/actions/connection.js#L16 But I will have to deal with the internal domain thing.
