### ISSUE TITLE
existsSync in not a function

### ISSUE THREAD

**Issue by mofodox** [dgraph-io/dgraph-js#29]
Hi there,

I created a react project app using the `create-react-app` CLI and installed dgraph and grpc via `yarn add`. And I'm currently facing an issue which it says `existsSync in not a function`. And when I clicked on the error, it brings me to the `grpc_extension.js`. 

Here's the screenshot to the error: [error_image](https://cl.ly/261S3M1J1q2m). Hope to hear from you guys soon! Thank you!

**Comment by gpahal** [comment]
Which version of grpc are you using?

**Comment by mofodox** [comment]
@gpahal I'm using the latest version of grpc which is 1.10.0

**Comment by mofodox** [comment]
@gpahal This is what I [found](https://github.com/grpc/grpc/issues/11435). What's your advice on this?

**Comment by gpahal** [comment]
Can you share a bit of your code which is causing this error?
I tried out grpc v1.10 for a sample program I have. I was not able to reproduce this issue.

**Comment by gpahal** [comment]
Oh! I just realized. This client is a node.js client and not for JS frontend. This is because of gRPC. It doesn't support browsers as it's based on C++ code and HTTP/2.
