### ISSUE TITLE
It's not possible to distinguish between errors

### ISSUE THREAD

**Issue by ondrowan** [dgraph-io/dgraph-js#35]
Since this library uses only native `Error`, it's hard to distinguish the reason why transaction failed. The only way at the moment is to compare error message, which is very cumbersome. I'd like to be able to do the following:

```
try {
    // some transaction code
} catch (e) {
    if (e instanceof errors.AbortedError) {
         // retry
    }
}
```

Does this make sense or is there any better way to achieve this?

**Comment by gpahal** [comment]
dgraph-js doesn't use different error types but uses global error constants, so you can do:
```js
try {
    // some transaction code
} catch (e) {
    if (e === dgraph.ERR_ABORTED) {
         // retry
    }
}
```

Look at file [src/errors.ts](https://github.com/dgraph-io/dgraph-js/blob/master/src/errors.ts) for all the error values.

**Comment by ondrowan** [comment]
I didn't realize those errors were instantiated only once. Thanks 👍

**Comment by felixfbecker** [comment]
This is not a good practice, because stack traces are generated at the time of instantiating the error. Therefor the error won't have a useful stacktrace
