### ISSUE TITLE
TLS client Authentication?

### ISSUE THREAD

**Issue by selmeci** [dgraph-io/dgraph-js#37]
Hi,

I would like to secure my connection with TLS.
How I can setup client authentication?

Thank you.
Best regards,
Roman

**Comment by gpahal** [comment]
You need to setup TLS as shown here: https://docs.dgraph.io/deploy#tls-configuration

On the client side, you need to add credentials to the DgraphClientStub constructor sa shown below:

```js
const dgraph = require("dgraph-js");
const grpc = require("grpc");

const clientStub = new dgraph.DgraphClientStub(
  // addr: optional, default: "localhost:9080"
  "localhost:9080",
  // credentials: pass your root certificates here
  grpc.credentials.createSsl(root_certs),
);
const dgraphClient = new dgraph.DgraphClient(clientStub);
```

**Comment by selmeci** [comment]
Hi @gpahal, thanks for hints ;).
There is some issue with TLS setup between dgraph and js but I found working solution.

**Comment by mkucharz** [comment]
@selmeci what is you working solution? I'm try many different thing without success... I tried common way and with nginx grpc ssl proxy. It look fro me like some kind of problem with "dgraph-js" library.

**Comment by selmeci** [comment]
@mkucharz Unfortunately I did not solve it directly and I have to use nginx grpc ssl proxy for authentication.

**Comment by mkucharz** [comment]
@selmeci maybe this will help if you still need it: https://github.com/dgraph-io/dgraph-js/issues/50
