### ISSUE TITLE
Some trouble with the final query

### ISSUE THREAD

**Issue by thewisewolfHoro** [dgraph-io/dgraph-js#45]
Like below,I get a [] at last.
I tried run the query part separately, it will work and I can get the correct result, and the data was successfully insert into the database.I hope some one can help me to explain that. XD

`Created person named "Alice" with uid = 0x8e

All created nodes (map from blank node names to uids):
blank-0 => 0x8e
blank-1 => 0x8f
blank-2 => 0x90
blank-3 => 0x91

{ all: [] }
Number of people named "Alice": 0

DONE!
`

**Comment by paulftw** [comment]
Closing the issue as it doesn't have a code sample to reproduce and has been stale for quite some time.

Feel free to post it as a question in our [community forums](https://discuss.dgraph.io/) or re-open if more details are available.
