### ISSUE TITLE
Query for a node, filtering using uid of child nodes (relations).

### ISSUE THREAD

**Issue by PraveenKumarPalai** [dgraph-io/dgraph-js#51]
If have a schema "Like" that has relations to User Schema(user_id) and Post Schema(object_id). How ca I query for the "Like" nodes that have ```user_id = (some_uid)``` and ```object_id = (some_uid)```.

**Comment by paulftw** [comment]
@PraveenKumarPalai your question is about the query language and not specific to dgraph-js.

Support Engineers and Community will be happy to help you if you post your setup and requirements to https://discuss.dgraph.io/

I'm closing the issue as it's outside the scope of the client library

**Comment by PraveenKumarPalai** [comment]
Thanks @paulftw! Do we have a slack channel for these type of discussions?

**Comment by MichelDiz** [comment]
Here https://dgraph.slack.com

**Comment by PraveenKumarPalai** [comment]
> Here https://dgraph.slack.com

Can you send me an invite. I am not able to login.
email: praveen@impulsiveweb.com
Thanks

**Comment by danielmai** [comment]
Hey @PraveenKumarPalai, I sent you an invite to our Slack community. Welcome!

**Comment by PraveenKumarPalai** [comment]
Thanks @danielmai :)
