### ISSUE TITLE
Update tests to use test ports for the Dgraph cluster.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph-js#55]
The tests should be updated to run against the Dgraph test cluster defined in this docker-compose.yml file: https://github.com/dgraph-io/dgraph/blob/43c8d38499fb8795e6e5bb5f6a5facf665f36d64/dgraph/docker-compose.yml

- [ ]  Alpha runs on gRPC port 9180.
- [X] Enterprise ACLs are enabled and require `groot` login (this is already done).

**Comment by danielmai** [comment]
When changing to port 9180 there's a test that fails when using the default constructor for the client stub, which defaults to port 9080:

https://github.com/dgraph-io/dgraph-js/blob/21563532863a01a639b4ddf4848e3de3de77b3e0/src/clientStub.ts#L58-L61

To fix this we should do one of two things (or both):

1. Remove this test that involves the default constructor
2. Remove setting a default address in an empty constructor (breaking the existing API).

Setting a default address when constructing a client connection doesn't happen in any of the other official clients. It's also such a small thing that it doesn't need to be tested for, and keeping it means the tests must always run with a Dgraph cluster on port 9080.

**Comment by paulftw** [comment]
@danielmai 
[this change](https://github.com/dgraph-io/dgraph-js/commit/7652bfee9185d1e7650e6f244ba2c49932ee5a60) allows specifying dgraph port via an env var:
`DGRAPH_SERVER_ADDR=localhost:9180 yarn test`

It also removes the constructor unit test.

Please re-open if you need anything else
