### ISSUE TITLE
API is not ergonomic

### ISSUE THREAD

**Issue by felixfbecker** [dgraph-io/dgraph-js#62]
It seems like the API is purely a generated gRPC client. This makes it very unergonomic for JavaScript in many places:

- None of the classes have constructors. For example, I can't pass the value directly to `new Value()`, instead I have to call `value.setStringVal('abc')`. One would expect an API more around object literals rather than getter and setter methods
- The API allows contradictory state. For example, what happens when I call both `setStringVal()` and `setIntVal()`?
- Some methods are confusingly named - e.g. `setSetJson()`
- There are no docblocks on any methods
- Some types are completely unclear how to use - e.g. `setGeoVal()` takes a `string` or a `UInt8Array`.

**Comment by campoy** [comment]
Hi @felixfbecker,

It is true this is a pretty thin layer built on top of the autogenerated gRPC code.
We are currently growing our teams to be able to have the bandwidth to improve all of our clients (and also provide new ones).

We will keep this issue open and track improvements, feel free to send more issues if you see other specific parts of the API that should definitely be fixed.

Thanks!

**Comment by zakmandhro** [comment]
@felixfbecker If you are looking for a higher level of abstraction for Dgraph, you may want to check out https://github.com/gverse/gverse, an open-source Object-Graph Mapper for Dgraph. It is built on dgraph-js.

Gverse allows you to define vertices as classes:

```typescript
const graph = new Gverse.Graph(
  new Gverse.Connection({ host: "localhost", port: 9080 })
)

class User extends Gverse.Vertex {
  type = "User"
  name: string
}
```
and then query, mutate, etc. with ease:

```typescript
const user = new User()
user.name = "Zak"
await graph.create(User)
```

Gverse also provides a friendlier API for connections, transactions, relationships (edges), marshaling/unmarshaling, querying, mutating, etc. You can see the usage details [in the integration tests](https://github.com/gverse/gverse/tree/master/src/test/integration).

I built Gverse for my startups and we are using it on multiple products. We'd love your feedback and contributions.

**Comment by campoy** [comment]
Wow, that's a great project @zakmandhro!

@hackintoshrao, could you make sure we add this to our docs on the part of unofficial clients?

Also, we should definitely send a t-shirt to @zakmandhro for the amazing work. Please send me an email with you address to francesc@dgraph.io and I'll make sure you receive one.

**Comment by Sceat** [comment]
Just started learning Dgraph, if you are open to suggestion i'd see a driver taking advantage of javascript's tagged template literals, would be pretty neat to build simply as so

```js
import dgraph from 'dgraph-js'

async function exemple() {
	const clientA = dgraph.connect('localhost:9080')
	const bar = 'bar'
	const first = 5
	await clientA.mutate(`
	{
		set: {
			_:a <foo> ${bar} .
		}
	}
	`)

	const result = await clientA.query(`
	{
		q(func: has(foo), first: ${first}) {
			foo
		}
	}
	`)
}

exemple()
```

minimalism :+1:

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8178). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
