### ISSUE TITLE
Mutate is not part of dgraph.API as of v1.1.0

### ISSUE THREAD

**Issue by markmssd** [dgraph-io/dgraph-js#74]
I'm using the sample test file to run `e2e` tests.

However, something is off in this simple test file when using DGraph `v1.1.0`:
https://github.com/dgraph-io/dgraph-js/blob/master/examples/simple/index.js#L71

If used against older versions, `<= v1.0.17`, it executes successfully.

**Comment by prashant-shahi** [comment]
@markmssd The dependency versions have been updated for the examples.

Thanks for pointing it out.
