### ISSUE TITLE
Documentation on pre-v7.6 examples should be removed

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph-js#88]
`examples/simple` has `index-pre-v7.6.js` according to docs it's for versions of node from 2017.
- We don't offer legacy code for other examples
- Support for all obsolete nodejs versions is not our goal
- node 7.6 was released in 2017, current LTS node is 10.16, latest is v12.11. There are no good reasons to support that environment, esp. when current dgraph-js is not supposed to be used with Dgraph pre-1.1
  - there's also a chance 7.6 refers to the V8 version, not nodejs version, in which case docs are misleading

To address all of these and simplify life for everyone we should just drop that pre-7.6 example and all references to it.
Users who cannot use async/await can either add transpiler to their toolchain or port examples to promises/then.

**Comment by paulftw** [comment]
@prashant-shahi thanks for dropping that old example, but now README contains references to a file that no longer exists: https://github.com/dgraph-io/dgraph-js/tree/master/examples/simple#run-the-sample-code

We should aim to always update code and docs in the same pull request.

**Comment by prashant-shahi** [comment]
@paulftw Alright remember to do that. For now, I have raised a PR for updating docs. Please do review it.
